"""Registry capability subpackage for Octopus SDK."""

from octopus_sdk.registry.authority_client import RegistryAuthorityClient
from octopus_sdk.registry.client import RegistryClient, RegistryClientError
from octopus_sdk.registry.models import (
    AckResult,
    AgentCard,
    AgentDiscoveryQuery,
    AgentRecord,
    ConversationCreate,
    ConversationRecord,
    ConversationProgressUpdate,
    DeliveryRecord,
    DeliveryPollResult,
    DiscoveredAgentRef,
    EnrollmentResult,
    EventRecord,
    HealthSummary,
    MessageRecord,
    MirrorOutcome,
    RuntimeHealthPayload,
    RoutedTaskRequest,
    RoutedTaskResult,
    RoutedTaskUpdate,
    TaskRecord,
    TargetResolutionPreview,
    TimelineEventPayload,
)

__all__ = [
    "RegistryAuthorityClient",
    "RegistryClient",
    "RegistryClientError",
    "AckResult",
    "AgentCard",
    "AgentDiscoveryQuery",
    "AgentRecord",
    "ConversationCreate",
    "ConversationRecord",
    "ConversationProgressUpdate",
    "DeliveryRecord",
    "DeliveryPollResult",
    "DiscoveredAgentRef",
    "EnrollmentResult",
    "EventRecord",
    "HealthSummary",
    "MessageRecord",
    "MirrorOutcome",
    "RuntimeHealthPayload",
    "RoutedTaskRequest",
    "RoutedTaskResult",
    "RoutedTaskUpdate",
    "TaskRecord",
    "TargetResolutionPreview",
    "TimelineEventPayload",
]
